// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/post/post.proto

package go_micro_srv_post

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Post service

type PostService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Post_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Post_PingPongService, error)
}

type postService struct {
	c    client.Client
	name string
}

func NewPostService(name string, c client.Client) PostService {
	return &postService{
		c:    c,
		name: name,
	}
}

func (c *postService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Post.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Post_StreamService, error) {
	req := c.c.NewRequest(c.name, "Post.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &postServiceStream{stream}, nil
}

type Post_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type postServiceStream struct {
	stream client.Stream
}

func (x *postServiceStream) Close() error {
	return x.stream.Close()
}

func (x *postServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postService) PingPong(ctx context.Context, opts ...client.CallOption) (Post_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Post.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postServicePingPong{stream}, nil
}

type Post_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type postServicePingPong struct {
	stream client.Stream
}

func (x *postServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *postServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *postServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *postServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Post service

type PostHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Post_StreamStream) error
	PingPong(context.Context, Post_PingPongStream) error
}

func RegisterPostHandler(s server.Server, hdlr PostHandler, opts ...server.HandlerOption) error {
	type post interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Post struct {
		post
	}
	h := &postHandler{hdlr}
	return s.Handle(s.NewHandler(&Post{h}, opts...))
}

type postHandler struct {
	PostHandler
}

func (h *postHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.PostHandler.Call(ctx, in, out)
}

func (h *postHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PostHandler.Stream(ctx, m, &postStreamStream{stream})
}

type Post_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type postStreamStream struct {
	stream server.Stream
}

func (x *postStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *postHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.PostHandler.PingPong(ctx, &postPingPongStream{stream})
}

type Post_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type postPingPongStream struct {
	stream server.Stream
}

func (x *postPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *postPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *postPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
